name: Fetch Insider Trades

on:
  workflow_dispatch:

jobs:
  run:
    runs-on:
      - self-hosted
      - macOS
      - ARM64
      - mac-runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          GOOGLE_SHEETS_KEY: ${{ secrets.GOOGLE_SHEETS_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python main.py
